### ISSUE TITLE
Scrolling in the thumbs-browser using mouse wheel don't work while hovering over selected image (UI Size >= Medium)

### ISSUE THREAD

**Issue by teadrinker** [bluescan/tacentview#133]
You might know this already, but using UI Size >= Medium, I suspect the selected thumb image is slightly too large, and it tries to scroll the selected thumb in its own frame...

**Comment by bluescan** [comment]
Thank you teadrinker. Hadn't actually noticed that one. I've been unable to repo after the High DPI rework in ae6753ea9e2c65ee261a8782a80b6251cec7b8bb.
