### ISSUE TITLE
[Small UI improvement] - Focus text box when renaming a file

### ISSUE THREAD

**Issue by DeliciousLines** [bluescan/tacentview#167]
When I rename a file it would be amazing to have the text box already focused so that I can directly edit the file name. Right now I need to click on it and then edit it, which is slightly annoying when renaming several files in a row.

Other than that I really enjoy this viewer, thank you for your work!

**Comment by bluescan** [comment]
Good idea. This is now committed at 945dfa5d2813a062a6e9d40700206f29147d3025.
If you are not setup to clone/build post again here and I can attach either a windows zip or deb.

**Comment by DeliciousLines** [comment]
Thank you! I do not have a clone/build setup, so I would not mind downloading the Windows zip.

**Comment by bluescan** [comment]
[tacentview_1.0.43.zip](https://github.com/bluescan/tacentview/files/15209918/tacentview_1.0.43.zip)
This has the fix. Thx for the suggestion.

**Comment by DeliciousLines** [comment]
Thanks!
