### ISSUE TITLE
Display cubemap mipmaps

### ISSUE THREAD

**Issue by Trider12** [bluescan/tacentview#174]
I would be nice if the viewer could display both faces and mipmaps for cubemaps. Currently it's only faces for cubemaps.

**Comment by bluescan** [comment]
agreed. Will leave this open until it's implemented.

**Comment by bluescan** [comment]
Implemented in f3a236cb7bbadc74fd9039826f8cfdbcbb437390. Test cubemap images in DDS, PVR, and KTX2 formats are in the TestImages/Cubemaps folder. All sides (including mipmaps) remain scrubbable.
