### ISSUE TITLE
Instead of transparent pixels, you get green pixels

### ISSUE THREAD

**Issue by Vladik01-11** [bluescan/tacentview#179]
I don't know what's wrong with this image, but all image viewers see just transparent pixels, when Tacent sees green color at all.
![tacentview_W17lyXVnhj](https://github.com/user-attachments/assets/913771c8-134e-4dc3-93dd-50f128b0d924)

The image itself (even on the github it is transparent)
![mouse](https://github.com/user-attachments/assets/c5bfb83d-d799-47c0-b333-869762db73d9)

**Comment by bluescan** [comment]
Hi Vladik, thanks for the report.

It's a colour-indexed (2-bit in this case) png with transparency. Tacent View wasn't loading palettized images with transparency properly. This has been fixed in 6db22c9dbd8221537b7afecebe60d3a3a840f0ec.
