### ISSUE TITLE
Animated WebP playback error

### ISSUE THREAD

**Issue by rellikmil** [bluescan/tacentview#186]
![изображение](https://github.com/user-attachments/assets/7ea55496-a86c-4764-a5bf-b48fa0d2da98)

Original is here - https://mathiasbynens.be/demo/animated-webp

**Comment by bluescan** [comment]
Thanks for the report. Yes, something definitely off -- I'm guessing untouched pixels from previous frames are incorrectly getting transparent pixels or something similar.

**Comment by bluescan** [comment]
Fixed in 2e4056f06dc98f79933b14309def97aeb51a1ad4
