### ISSUE TITLE
Single Channel images not showing up

### ISSUE THREAD

**Issue by dadiborn** [bluescan/tacentview#26]
Thanks for amazing viewer but today i found that if image has single channel (openEXR in my situation) it shows nothing.
Here is exr file: [https://drive.google.com/file/d/1Ge9Xzq5E95ZfvDIWtuytkyNudVpXJjTY/view?usp=sharing](https://drive.google.com/file/d/1Ge9Xzq5E95ZfvDIWtuytkyNudVpXJjTY/view?usp=sharing)

**Comment by bluescan** [comment]
Hi dadiborn. Confirmed something is up (can open the file in affinity photo ok)... but in tacentview it's coming in with 1x1 dimensions.

**Comment by bluescan** [comment]
Note to self: It is related to: https://github.com/AcademySoftwareFoundation/openexr/issues/214

**Comment by bluescan** [comment]
Commit fda46d25 fixes. V1.0.23
[tacentview_1.0.23.zip](https://github.com/bluescan/tacentview/files/6838303/tacentview_1.0.23.zip)
