### ISSUE TITLE
Zooming the image doesn't take up the entire workspace

### ISSUE THREAD

**Issue by Frousties** [bluescan/tacentview#30]
![image](https://user-images.githubusercontent.com/26504212/158856061-dd442d67-5d17-46ff-811e-7cd89c212bd2.png)
![image](https://user-images.githubusercontent.com/26504212/158856095-1a948a42-a807-4ddf-a2ff-2e071d219507.png)
> Yeah, I wanted the displayable area to maintain aspect under zoom...but also not sure how much I like it either -- it especially breaks down viewing extremely narrow images.

**Comment by bluescan** [comment]
Commit 77e5b26ab10bfff5ac46a6f09aee12024dfbf98a : Default to NOT use a fixed aspect work area. It is now an option (FixedWorkAreaAspect) to turn it on in the 'Display' tab of the preferences (the 'Display' tab used to be called 'Background'). Also fixed a background drawing bug that was sometimes showing a pixel-width line outside of the image.

This commit also includes removal of some questionable UV margin code. I'm going to let this settle a bit b4 closing. Have tested rotate, crop, zoom, pan -- but not thoroughly.

**Comment by bluescan** [comment]
Yup! It was supposed to give the old behaviour back. Fixed in e60c3f7dad15054e45db898d48410ffaad7e5acd
Thanks for testing.
