### ISSUE TITLE
[Suggestion] Option to reset the zoom when switching image

### ISSUE THREAD

**Issue by Frousties** [bluescan/tacentview#31]
Pretty self-explanatory, navigating through folders with images of multiples sizes can get a bit messy because of that. Maybe put a 'default zoom mode' option in the preferences would fix that? Since zooming in or out resets it to 'Zoom user'.

> Yup. Agree.

**Comment by bluescan** [comment]
Implemented in 825aaaf0f4607c24bd121fe0ba277966e1dfe310. Controls what zoom mode to use when displaying a new image. The setting is available in prefs->interface. Keep: No change to zoom mode when switching images. Fit: Image is zoomed to fit display area no matter its size. Downscale: Shows it at 100% zoom unless image is too big and needs downscaling. OneToOne: One image pixel takes up one screen pixel.
