### ISSUE TITLE
[Suggestion] Option to close the program with 'Escape'

### ISSUE THREAD

**Issue by Frousties** [bluescan/tacentview#32]
Some other image viewers have this feature (and sometimes by default), and I think it helps speeding up the workflow when going through multiple pictures.

> Sure. FYI Alt-F4 currently works.

I am aware of Alt-F4 but using only one button compared to having to cramp my hand for two quite far apart button feels better IMO.

**Comment by bluescan** [comment]
Hi. Thanks for taking the time to enter all your suggestions as separate issues. I've fixed this one in eac8607d.

"Option to allow using Esc key to quite app. Enabled by default. See Preferences->Interface to enable/disable"
