### ISSUE TITLE
'Basic View' mode doesn't restore the interface and settings as they were

### ISSUE THREAD

**Issue by Frousties** [bluescan/tacentview#34]
For example, when I exit 'Basic View', the 'Nav bar' disappears and the 'Auto Property Window' setting gets disabled. I don't really like that.

> I can look at that sometime.

**Comment by bluescan** [comment]
This will probably be next fix. It currently overwrites specific settings when you enter basic mode, and just resets to default when you exit. It would be much better if basic mode didn't modify the settings and we only store whether basic mode is enabled or not, then you'd exit to what you had before.

**Comment by bluescan** [comment]
This one was surprisingly quite a bit of work to get right. Basically support for profiles was added. Currenly there are two of them: Main and Basic and they can both be customized as desired and are saved in the cfg file. The defaults for each are different. The preferences window now supports resetting just current the category/tab, the entire current profile, or everything (all profiles).
