### ISSUE TITLE
Images are incorrectly centered at some window sizes

### ISSUE THREAD

**Issue by Oddwarg** [bluescan/tacentview#40]
Small images appear blurry at some window sizes because the image centering logic at TacentView.cpp line 975 is incorrect. This can be fixed by replacing the block with the following:

```
float offsetW = tMath::tRound((draww - w) / 2.0f);
left	+= offsetW;
right	= left+w;

float offsetH = tMath::tRound((drawh - h) / 2.0f);
bottom	+= offsetH;
top		= bottom+h;
```

Blurry, incorrect:
![blurry](https://user-images.githubusercontent.com/1974401/159063457-1615beeb-29a6-44a8-9f97-289a0e41ff1b.png)
Clear, correct:
![correct](https://user-images.githubusercontent.com/1974401/159063481-1d2532e0-38ee-4569-bb40-3801d97aa7ad.png)

**Comment by bluescan** [comment]
Thanks for the fix. It has been tested/pushed in 332a17c62024225cb6247f8014cdce1fcb8d7bba
