### ISSUE TITLE
The first frame of animated gifs with transparency contains uninitialized (garbage) pixels

### ISSUE THREAD

**Issue by Oddwarg** [bluescan/tacentview#41]
Unsure if this is the correct project to report this bug, but the problem is that transparent pixels are allocated, but never initialised to any value for the first frame in a gif file. This can be fixed by inserting the line
`memset(FrmPict, 0, Width * Height * sizeof(tPixel));`
at line 47 of tImageGif.cpp.

Incorrect, garbage background:
![garbage](https://user-images.githubusercontent.com/1974401/159065376-313e34d1-0e60-48c4-87e5-58deb290cbda.png)

Correct, clean background:
![fixed](https://user-images.githubusercontent.com/1974401/159065432-d5330f75-141b-4a91-a527-abb4f1822324.png)

**Comment by bluescan** [comment]
It's a fine place to report this -- plus you supplied the fix which is even better. It's fixed in the tacent library. You'll probably need to reconfigure to get cmake to fetch the latest tacent lib.
