### ISSUE TITLE
[Suggestion] Restore Maximized/Fullscreen view states

### ISSUE THREAD

**Issue by kutu** [bluescan/tacentview#42]
Currently only window size is restored.

If I maximize window, quit, open again, the size will be correct (looks like maximized), but window is not truly maximized.

I prefer to have a fullscreen view from the start, and I set `q` keybind for quick exit.

**Comment by bluescan** [comment]
Yeah. I can look at this. Currently the fullscreen setting (Alt-Enter fullscreen -- without the window title-bar) is not saved in the config at all.

Note to self: It probably makes sense to store the window geo (width/height offsets) in the global section of the config along with the fullscreen mode, Currently the win geo is stored per profile but behaves as if it's global (it would be weird if the window started snapping all over the place when changing profiles), so I think both of these should be global.

**Comment by bluescan** [comment]
Fixed in 0063921d5cdffd1f0782ebef14b8c15a531bd087
