### ISSUE TITLE
[Bug] Filename encoding problems

### ISSUE THREAD

**Issue by kutu** [bluescan/tacentview#43]
Tacent won't open file if it has Cyrillic letter (it opens with blank window).
try rename a file to `ы.png`

Tacent title bar incorrectly display filenames with chars that not English.
![image](https://user-images.githubusercontent.com/228802/174075972-710c6de3-e356-4d50-ad59-2bfa82f44927.png)

**Comment by bluescan** [comment]
![KubuntuCyrillic_Screenshot_20220618_134124](https://user-images.githubusercontent.com/19311462/174456578-29927755-4e8b-49d5-89d9-0b21cda73937.png)

**Comment by bluescan** [comment]
![image](https://user-images.githubusercontent.com/19311462/174456705-aa9b55d7-beeb-45b9-beb8-f2b057e0dfe1.png)

**Comment by kutu** [comment]
i use windows 10
did you use precompiled version?
i use tacent v1.0.27

if i open image with double click, it just blank
if i try drag and drop image, tacent opens next image in folder

**Comment by bluescan** [comment]
Note, the 2 screens above are without making any changes/fixes... so might need some more information. It is worth noting that in windows I do have the following option set (as I needed utf-8 to show u properly in console output):

![image](https://user-images.githubusercontent.com/19311462/174456974-26ce2740-e434-4fb4-bc92-eaa9b8fc50af.png)

**Comment by bluescan** [comment]
I'll try the release of 1.0.27. I don't have windows 10 tho.

**Comment by bluescan** [comment]
Works locally with the released 1.0.27. Also tried double-clicking and drag-and-drop without issue. I'll need to try (but can't right now) without the checkbox above un-checked. glfw expects the title in utf-8 encoding which is what is being passed.

**Comment by kutu** [comment]
after enabling "beta" option, it started to work as expected

**Comment by bluescan** [comment]
Yeah. Hopefully you're happy with this for now (as a bonus, you can now see more unicode characters in the command prompt etc). In truth you should not really need to have this option checked if the viewer and its base libraries were calling the UNICODE and _UNICODE versions (UTF16 on windows) OS calls everywhere... It's a bit of work to fix, but I'll leave this issue open for now. Thanks for the report.

**Comment by bluescan** [comment]
As of 03e7cb466a62cfacdf205ba0a9dc6bc25d5dc973 the Beta flag is no longer necessary.

**Comment by kutu** [comment]
- file name in title is showing correctly
- drag and drop image to tacentview is working

- double click on file with Cyrillic symbols is still not working (I'm not using "Beta" flag). It opens next file in folder. Accidentally if there is only one file in folder, then it opens file that I wanted


using `tacentview_1.0.43.zip`

**Comment by bluescan** [comment]
Hi kutu. Thanks for the report. I'll re-open this. Looks like it's 'nearly' all working ;)

**Comment by bluescan** [comment]
Fixed in 6006aa0738fc062f03206c921aa3a9e271ca8543
'Beta' checkbox no longer necessary to have the viewer open files with cyrillic characters by double-clicking.
