### ISSUE TITLE
No way to hide reticle

### ISSUE THREAD

**Issue by kutu** [bluescan/tacentview#86]
Maybe allow left click outside of the image to hide reticle.
Or reticle should appear after first left click on the image, after switching to different image - reticle disappear.
Allow disabling reticle completely in preferences.

**Comment by bluescan** [comment]
Yeah -- we can do something about this. At one point the reticle auto-hid along with the onscreen buttons... maybe the reticle modes are a) Always On. b) Auto-Hide c) On Select d) Always Off.
 c) would be what you have above: click outside = hide. Click inside = show. Image change = hide.

**Comment by bluescan** [comment]
Fixed in ac6884c046bd7f79b08a83c75c95f498d992cacb
