### ISSUE TITLE
New format suggestion: QOI

### ISSUE THREAD

**Issue by BrothaOnAcid** [bluescan/tacentview#88]
any plans to include QOI import ?
its very lightweight, written in c. no deps

[https://github.com/phoboslab/qoi](https://github.com/phoboslab/qoi)

**Comment by bluescan** [comment]
Should be able to add this... and reminder to self, I also want to add ARM's simple .astc format directly (without needing ktx/dds).

**Comment by bluescan** [comment]
Loading and Saving of QOI files implemented in f69ff1326100acf56980d544b0b70b5025bb343e
![image](https://user-images.githubusercontent.com/19311462/201439550-821733a5-9e39-4212-9604-0a9d819df8cd.png)
