### ISSUE TITLE
Delete confirmation dialog doesn't react to keyboard

### ISSUE THREAD

**Issue by kutu** [bluescan/tacentview#93]
- press `delete` key
- confirmation dialog appears
- `enter` key doesn't delete file
- `tab` key not going through available buttons in dialog
- `escape` key doesn't close dialog (aka cancel)

**Comment by bluescan** [comment]
85c1b2d2a5653cf7c8c7695087c6fbc7a9688b52 Modifies focus behaviour for this dialog and the shift-delete dialog. Focus goes to the OK. Enter deletes the file (not built-in in ImGui as it requires a custom button wrapper, but I prefer it) .

Tab usually cycles through input widgets only (again, in ImGui), but dir keys can be used instead to select Cancel.  Esc is also not 'close' by default, so will need to select Cancel and press Space/Enter. In any case, can now use dir keys and space/enter to press selected button.
