### ISSUE TITLE
[Bug] CLI args broken in Linux

### ISSUE THREAD

**Issue by Frousties** [bluescan/tacentview#94]
Hello,
Not sure since how long it happened, but CLI arguments do not work anymore on Linux, also meaning you can't open images by file association.

I *think* it's due to the variable ``CurrImageFile`` not being set, which always makes it fall back to the last used picture instead of the selected one, since setting it like on the Windows side works.

I *would* make a PR for this, but I feel like it would just make things more complicated on your end x)

**Comment by bluescan** [comment]
Thanks Frousties. That was exactly the issue. Fixed in da4acd0ee5dfca7d3ac18e28627a569e977aed33
(The issue was only recently introduced while prepping for more commandline options. It was not present in the last official release).
