### ISSUE TITLE
Animated webp breaks or crashes on open with some files but not others

### ISSUE THREAD

**Issue by Crystalwarrior** [bluescan/tacentview#96]
[ex.zip](https://github.com/bluescan/tacentview/files/10855568/ex.zip)
attached are two animated webp files, one I could open and one I couldn't. First time I opened the "Confused.webp" example file as I installed the program, it displayed broken rows but could read animation just fine, however on subsequent launches the program just crashes (happened after I opened the "Shy.webp", it stopped letting me open the other file)

**Comment by bluescan** [comment]
Thanks for the example files. I can repo... I'll follow up

**Comment by bluescan** [comment]
The crash is fixed at f81d55c1735ceb7fdb93b8bba3b813d0c39287bc but the files don't yet look correct.
Tacent's webp loading code while demuxing still needs a little attention though.

**Comment by bluescan** [comment]
Fixed in 65922ccc537d61871d4c5324b252a8f3b8382b58
Also look for 'Override Background' in the WebP properties window.
Attached is a zip with the change as it is not released yet.
[tacentview_1.0.36.zip](https://github.com/bluescan/tacentview/files/10950405/tacentview_1.0.36.zip)
